[project]
name = "ppo-atari-pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["gymnasium>=1.2.1", "opencv-python>=4.12.0.88", "torch>=2.9.0"]
